### ISSUE TITLE
Migration from ADAL to MSAL?

### ISSUE THREAD

**Issue by marconfus** [microsoft/Intune-Resource-Access#104]
It looks like the code uses the ADAL authentication, this document (https://developer.microsoft.com/en-us/identity/blogs/end-of-support-timelines-for-azure-ad-authentication-library-adal-and-azure-ad-graph/) mentions, that this will stop working in July 2022.

Are there any plans to migrate to MSAL?

**Comment by darba** [comment]
Yes. We are working on updating cmdlets that use MSAL and are aware of the ADAL sunset date.
