### ISSUE TITLE
Impossible to check the value of PROVIDER_NAME_AND_VERSION in the AAD or Intune portal

### ISSUE THREAD

**Issue by HirokiPpr** [microsoft/Intune-Resource-Access#109]
> IntuneScepServiceClient.java

・ PROVIDER_NAME_AND_VERSION = "Information used to identify the product and its version"
We checked that this value is used in the source code as User-Agent in the SCEP Intune API.
Therefore, I think AAD and Intune are pulling this value.
However in testing, it was not available to view on any screens accessible from the Intune, AAD management screens. 
Is there a screen or function where Intune administrators can see where PROVIDER_NAME_AND_VERSION is being used?

**Comment by tynidev** [comment]
This is not something that will show up in the portal.  This is a value that is used in Intune logging and diagnostics to provide troubleshooting.
