### ISSUE TITLE
About when to do SendSuccessNotification Method in IntuneScepServiceClient.java

### ISSUE THREAD

**Issue by HirokiPpr** [microsoft/Intune-Resource-Access#110]
>IntuneScepServiceClient.java

From the [documentation](https://docs.microsoft.com/en-us/mem/intune/protect/scep-libraries-apis#sendsuccessnotification-method), I've understood that the certificate will be processed by the certificate authority after it is issued as follows:

1) Client certificate is issued,
2) The required information on the issued client certificate is gathered and Intune is notified with the SendSuccessNotification method
3) (If the method finishes successfully) The certificate is distributed to mobile devices

Is this understanding correct?
*We understand that swapping 2) and 3) is a deprecated order.

**Comment by tynidev** [comment]
It is not clear what you are asking. But that is the order things should happen yes.
