### ISSUE TITLE
Azure Active Directory Graph >> Microsoft Graph perms mapping issue - Did not find service named 'ScepRequestValidationFEService' listed in Microsoft.Graph

### ISSUE THREAD

**Issue by appsdesh** [microsoft/Intune-Resource-Access#111]
@tynidev 
I started seeing this issue on a newly created app registration. (Existing apps are working fine) 

During this new app registration process, I can't assign `Azure Active Directory Graph` API permissions to the app as mentioned in the https://docs.microsoft.com/en-us/mem/intune/protect/certificate-authority-add-scep-overview 

![Screen Shot 2021-09-27 at 10 41 28 AM](https://user-images.githubusercontent.com/3487483/134958494-f9dc621b-8360-4a1f-b9b3-ba725d2a5542.png)
 
I see a depreciation message in the Azure portal for adding API permissions and `Azure Active Directory Graph` is disabled under `Legacy APIs`

![Screen Shot 2021-09-27 at 10 43 22 AM](https://user-images.githubusercontent.com/3487483/134958717-cade3b73-b033-43a4-a934-1a2302ea5693.png)

This results in an error 
`Did not find service named 'ScepRequestValidationFEService' listed in Microsoft.Graph discovery service list.`

**_Could you please provide info on how do I map `Active Directory Graph > Application > ReadAll` permissions to a the new `Microsoft Graph` APIs permissions?_**

I noticed a similar issue https://github.com/microsoft/Intune-Resource-Access/issues/85 but that was a config issue. My issue persists beyond the resolution workarounds suggested there.

**Comment by tynidev** [comment]
This is something that we are addressing shortly. The AAD team has deprecated this API and we are updating our library in accordance.
