### ISSUE TITLE
no valid module file was found in any module directory

### ISSUE THREAD

**Issue by jakobems** [Microsoft/Intune-Resource-Access#23]
Hi,

when I try to import the module I'm getting this error:

> Import-Module : The specified module 'IntunePfxImport.psd1' was not loaded because no valid module file was found in any module directory.
> At line:1 char:1
> + Import-Module IntunePfxImport.psd1
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ResourceUnavailable: (IntunePfxImport.psd1:String) [Import-Module], FileNotFoundException
>     + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
> 

I'm a PS noob but should there not be anywhere the Microsoft.Management.Powershell.PFXImport.dll file?

Thanks for help and best regards
Jakob

**Comment by darba** [comment]
Hi Jakob,

I've updated the readme documentation. You need to make sure you first build the solution and have the correct path to the psd module when you try to import it.

This feature isn't live yet but should be soon.

Cheers!

**Comment by darba** [comment]
Closing this out. Let me know if this is still an issue and we will re-open things.

Cheers
