### ISSUE TITLE
Deploy the code to Intune

### ISSUE THREAD

**Issue by cowon78** [microsoft/Intune-Resource-Access#58]
Are you able to provide the detailed steps to deploy the code to Intunes so that I am able to import S/MIME certificates in pfx format to Intune and deploy the pfx certificates to users?

**Comment by darba** [comment]
There is a short cookbook of commands that you can call here:  https://github.com/microsoft/Intune-Resource-Access/blob/develop/src/PFXImportPowershell/README.md

Here is also a support page here: https://docs.microsoft.com/en-us/intune/protect/certificates-imported-pfx-configure

If you still require help, I would contact your Microsoft Support Rep.
