### ISSUE TITLE
Unable to instantiate the IntuneScepServiceClient (Java)

### ISSUE THREAD

**Issue by mstenback** [microsoft/Intune-Resource-Access#60]
Attempt to instantiate `IntuneScepServiceClient` fails without error message. 

The best I can tell, the cause seems to be the value of `intuneResourceUrl`, which is set in the `IntuneClient` -class (line 83): `https://api.management.microsoft.com`

That domain no longer exists. I guess it has been replaced by the Microsoft's Graph API?

Will there be an update to the csrValidation -library that fixes this issue?

**Comment by tynidev** [comment]
This URL is not used as an endpoint but instead as a resource to be requested.  It was never a valid URL and isn't supposed to be.
